### ISSUE TITLE
Packaging Todo List

### ISSUE THREAD

**Issue by dmcglinn** [klocey/partitions#16]
## Code Cleaning
- [x] should we keep the long doc string at the top of partitions.py that introduces the purpose and contents of the script? Is this better placed elsewhere?
- [ ] add more annotation to the algorithm portion of the code
- [x] clean up superfluous stray annotations
- [x] make sure that function arguments are defined in clear and concrete ways. Link terms in the functions back to terms used in the manuscript.  For example part in the manuscript was referred to as an element of a partition. This should be made clear in the annotation. 
- [x] ensure that part refers to an element of a partition and parts refers to multiple elements of a partition
  - this is going to require changing object names in the code
- [ ] NrParts function
  - add more explanation of function's purpose
  - add citation to sage code
  - decide if there a namespace issue with this function because a function of the same with almost the exact same code exists in Sage
- [x] drop hash bang in partitions.py
- [x] import division from future
- [ ] rand_parts function
  - method best requires a file that has which algo is best for a given Q-N combo
  - decide what algo to use when Q-N combo is outside our knowledge
- [x] omit function numparts_QNK
## Code Testing
- [x] add test on function NrParts
  - test should check that NrParts returns the correct integer for various combos of Q and N
- [x] add test to check for bias in algos
  - this will compare the moments of the random samples of the feasible set to the moments of a completely enumerated feasible set

**Comment by klocey** [comment]
Beautiful list of to-do's. I'll work on them. I also updated the print statements in pypartitions for python 3 and started addressing issues raised by others.
